# Generated by Django 3.0.3 on 2020-03-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='direct_reports',
            field=models.ManyToManyField(related_name='_person_direct_reports_+', to='survey.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='peers',
            field=models.ManyToManyField(related_name='_person_peers_+', to='survey.Person'),
        ),
    ]
