# Generated by Django 3.0.3 on 2020-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200304_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managersurvey',
            name='person',
        ),
        migrations.RemoveField(
            model_name='peersurvey',
            name='person',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='managersurvey',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peersurvey',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Person'),
            preserve_default=False,
        ),
    ]
